                               Mental Health Risk Analysis System Using Python and NumPy

Making a dataset according to me which will include

Factor            Meaning

Sleep	         hours per day
Screen           Time	hours per day
Workload	     1–10 scaling
Mood	         1–10 scaling
Exercise       	 hours per week

where rows represent users and columns will represent mental health factors.

In [30]:
import numpy as np
data=np.array([[6, 8, 7, 4, 1],
    [8, 5, 4, 7, 3],
    [4,10, 9, 3, 0],
    [7, 6, 5, 6, 2],
    [5, 9, 8, 4, 1]
])
data

array([[ 6,  8,  7,  4,  1],
       [ 8,  5,  4,  7,  3],
       [ 4, 10,  9,  3,  0],
       [ 7,  6,  5,  6,  2],
       [ 5,  9,  8,  4,  1]])

In [31]:
#Lets normalize data so that all features can lie in a range i.e 0-1.
normalized_data = (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))
print(normalized_data)#Here, we are using axis=0 because we are normalizing columns, that represents features.

[[0.5        0.6        0.6        0.25       0.33333333]
 [1.         0.         0.         1.         1.        ]
 [0.         1.         1.         0.         0.        ]
 [0.75       0.2        0.2        0.75       0.66666667]
 [0.25       0.8        0.8        0.25       0.33333333]]


In [32]:
#Giving weights to each factor 
weights=np.array([0.25,0.20,0.25,0.20,0.10])
weights

array([0.25, 0.2 , 0.25, 0.2 , 0.1 ])

In [33]:
#Calculating risk score
risk_score = np.dot(normalized_data, weights)
risk_score

array([0.47833333, 0.55      , 0.45      , 0.49416667, 0.50583333])

In [38]:
#Calculating risk level
risk_level = np.where(
    risk_score < 0.4, "Low",
    np.where(risk_score < 0.7, "Medium", "High")
)

In [39]:
print("Risk Scores:", risk_score)
print("Risk Levels:", risk_level)

Risk Scores: [0.47833333 0.55       0.45       0.49416667 0.50583333]
Risk Levels: ['Medium' 'Medium' 'Medium' 'Medium' 'Medium']


                       “This project is for awareness and data analysis, not medical diagnosis.”